import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {mask,distance,key,area} from './几何核算.mjs';
const dir=path.dirname(fileURLToPath(import.meta.url));
const read=f=>JSON.parse(fs.readFileSync(path.join(dir,f),'utf8'));
const write=(f,o)=>{fs.mkdirSync(path.dirname(path.join(dir,f)),{recursive:true});fs.writeFileSync(path.join(dir,f),JSON.stringify(o,null,2)+'\n');};
const src=read('sources/父包直接对象.json'),surface=read('evidence/地表采样.json'),near=read('evidence/浅层采样.json');
const ground=new Map(surface.columns.map(c=>[key(c),c]));
const nearMap=new Map(near.columns.map(c=>[`${c.x},${c.z}`,c]));
const hash=f=>crypto.createHash('sha256').update(fs.readFileSync(path.join(dir,f))).digest('hex');
const pctx={civilization:'CIV-001 人类三域联盟',regional_family:'山地西来接驳前沿；东域山地适应与中域转运行为交接，不把方位名 west 等同西域',technology:'成熟前现代石木、台地、挡护、步级；魔法不能替代工程或供给',users:'两户家庭、修理工、值守复核者、少量随货到达者；具体户籍与任命未证',maturity:'EARLY_GROWTH 的条件性演化提案；非已发生历史',fabric_observation_state:'EXISTING_FABRIC_PARTIAL',evolution_logic:'EXISTING_EVOLUTION',existing_note:'地表和近地切片已读；未认定历史为空白，深部存在人工/生成结构位置证据。'};
const boundary={horizontal:'CELL_CENTER_MASK',cell_definition:'整柱 [x,x+1)×[z,z+1)，中心 (x+0.5,z+0.5)；本包发布的显式 cells 为判定依据',tie_rule:'与几何核算.mjs 的半开奇偶射线规则一致；边缘不由 Builder 重算并猜测',vertical_boundary_semantic:'仅规划水平使用包络；不是任意深度施工权。基础、门扇、悬挑及滴水不得侵入保护通行体积；深部内容一律保留。',edge_tolerance:0,adjustment_strip:'只允许在本户 cells 内调整；超出需最小接口修订，不自动取得公地'};
function stats(cells){const cc=cells.map(c=>ground.get(key(c))),nn=cells.map(c=>nearMap.get(key(c)));const states={};for(const c of cc){const n=surface.palette[c[4]];states[n]=(states[n]||0)+1;}return {columns:cells.length,ground_y_range:[Math.min(...cc.map(c=>c[3])),Math.max(...cc.map(c=>c[3]))],surface_states:states,canopy_columns:cc.filter(c=>c[6]||c[7]||c[8]).length,water_columns:cc.filter(c=>c[5]!==null).length,above_ground_nonair_columns:nn.filter(c=>c.state_ids.slice(25).some(i=>!['minecraft:air','minecraft:cave_air','minecraft:void_air'].includes(near.palette[i]))).length,air_within_24_below_columns:nn.filter(c=>c.state_ids.slice(0,24).some(i=>['minecraft:air','minecraft:cave_air','minecraft:void_air'].includes(near.palette[i]))).length};}
const parcels=src.parcels.map((p,i)=>{const cells=mask(p.polygon);const yard=cells.filter(([x,z])=>i===0?x>=752&&x<758&&z>=1628&&z<1631:x>=776&&x<780&&z>=1627&&z<1629);const apron=cells.filter(([x,z])=>distance(x+.5,z+.5,p.frontage)<=1.5);const reserved=new Set([...yard,...apron].map(key));const build=cells.filter(c=>!reserved.has(key(c)));return {id:`R2-P${i+1}`,source_object:p.id,source_revision:'MP-P04-r1',authority:'DESIGN_PROPOSAL',name:i===0?'下肩修理值守户':'上沿复核短宿户',polygon:p.polygon,boundary_semantic:boundary,cells,frontage:p.frontage,households:1,statistics:stats(cells),allocation:{gross_columns:cells.length,private_open_yard:{cells:yard,area:yard.length,role:i===0?'低肩家庭日常露天使用，与修理件及来客分开':'西侧浅舌部家庭露天小院，保留生活空间而不塞入第三户',adjustment:'允许等面积移位到同户可直达、未侵入通路的连通区域，至少保留2格短边；不改变公共接口'},private_frontage_apron:{cells:apron,area:apron.length,role:i===0?'短时收件/交件和门内停步；工件不存放到公共路带':'少量复核等待与门内停步；短宿者不在东口排队',adjustment:'入口可沿本户 frontage search segment 移动；不得把坡差处理移到公共净空'},architectural_search_mask:{cells:build,area:build.length,semantic:'可探索建筑占地的最大搜索区，不是建筑轮廓、必建面积或已证可居住面积'}},density_intent:i===0?'较宽修理户用地，作业—家庭前后分离；高低两肩相接，体量可分段':'小院放在西舌，较完整的东部承担居住/复核；允许 Builder 比较垂直混用和错时使用',future_growth:'不得增加户数或侵占公院；若房间、通路和生活容量不能共存，报最小上游问题。'};});
write('planning-data.json',{id:'MP-P05R2-NORTH-FRONTAGE-ENSEMBLE',test_id:'MP-P05R2',revision:'r1',scale:'URBAN_ENSEMBLE',authority:'DESIGN_PROPOSAL',state:'HANDOFF_READY',review_status:'AWAITING_GPT_AND_OWNER_REVIEW',regression_verdict:null,world_writes:0,world_write_authorization:false,source_package:'MP-P04-WEST-APPROACH/r1/PACKAGE-01',context:pctx,parcels,capacity:{households:2,gross_parcel_columns:269,continuous_polygon_area:273,private_yard_columns:26,private_frontage_columns:49,architectural_search_columns:194,search_area_is_not_floor_area:true,public_space_accounted_here:0,public_accounting_owner:'MP-P04 PACKAGE-03',overnight_guest_target:{range:[0,2],authority:'PLANNING_ASSUMPTION',note:'P02最多同时两名短宿者，不构成新户；Builder 须证明家庭功能不被占用，否则报容量冲突'},local_food_production:'NOT_ASSUMED',supply:'外部按批次供应；日需、土地用益与公共服务协议未获本轮批准'},growth:[{id:'R2-G1',authority:'PLANNING_ASSUMPTION',pressure:'西来批次货物不宜直接负重上坡',actors:'地方共同体与转运者',knowledge:'沿线坡差和卸载需要可为当事人所知；不把深部实体坐标当作历史知识',choice:'先分批首卸，再手提/轻载向东',response:'SPACE-01 与 LANE-01/02 构成先于户用围合的公共关系',feedback:'停留产生小修理与交割复核需求'},{id:'R2-G2',authority:'DESIGN_PROPOSAL',pressure:'反复到货需要就近小修理与复核值守',actors:'两户与公院使用者协商',choice:'修理靠较低到达肩；复核靠较高东口，均以保留公共通行为用地前提',response:'不等宽两户、不同门前高程、私院留在各户内部',feedback:'临院价值增高可能挤占公共路，因此固定门前通行与院内停步'},{id:'R2-G3',authority:'DESIGN_PROPOSAL',pressure:'少量滞留与下一批到货形成峰值',actors:'复核户、到货者与公共接口协调方',choice:'短宿最多两人，收件及洁污时段分开；拥堵时减批、停接单，不扩户',response:'P02保持小型家庭复合体；SPACE-01不转成私人客栈场院',feedback:'供给或通行持续失败才触发上游修订，不预画扩张地块'}],programs:[{id:'R2-PROGRAM-01',parcel:'R2-P1',required:['完整一户的睡眠、炊食、储藏、日常生活与卫生安排','小修理、工具及一批待交件暂存','值守与临院收交界面','可独立于来客停留使用的家庭小院'],excluded:['冶炼/连续高温重锻造厂','整队驮畜入户','公院作私人货仓'],magnitude:'家庭规模作业；一批在制/交接，拒绝用无限积压证明扩地',adjacency:['修理与低肩收件近邻','家庭日常不以穿过工作危险面为唯一通路'],builder_to_prove:'Plan/Section 中证明净可用空间、入口、层间通路和储物后仍完整；不以194列搜索总量当容积证明'},{id:'R2-PROGRAM-02',parcel:'R2-P2',required:['完整一户家庭生活','临轻载出口的接单与复核','0–2名随货者的短时过夜能力，与常住家庭区分','家庭小院和洁净小储备'],excluded:['第三常住户','开放式客栈/多人通铺扩容','占东口长期候检'],magnitude:'复核一次一小批；过夜上限2为规划假设，需以生活空间证明',adjacency:['复核入口朝LANE-04上段','短宿不以家庭小院作为公共穿行捷径'],builder_to_prove:'不得静默删除短宿/家庭功能以适配地块；若适应后仍不相容则返回容量冲突'}],architecture_kit_requirements:['共同文明石木构造语言、功能明确的公共—家庭阈限','P01与P02须能适应不同高程肩部，不能整片统一平台','支持浅窄地块混用、错时服务和可选择的垂直组织','保留家庭小院、低量暂存与服务接口；不指定房间、层数、屋顶、材料配方或基础结构'],implementation_sequence:['核实公共接口责任人与本轮局部基线；先联合处理路带和门前断面','两户分别开展 Architecture Design，复核功能净尺度与家庭/来客分流','闭合设计冻结HOLD并复核依赖版本','仅在未来明确授权后才可施工；本轮无写入步骤']});

const profiles=read('evidence/公共路纵断面.json');
const interfaces=[];
for(const lane of src.lanes){const cells=surface.columns.filter(c=>distance(c[0]+.5,c[1]+.5,lane.points)<=lane.width/2).map(c=>c.slice(0,2));interfaces.push({interface_id:'R2-IF-'+lane.id,interface_revision:'r1',role:lane.name,source_object:lane.id,source_revision:'MP-P04-r1',status:'DESIGN_PROPOSAL_LOCAL_BASELINE',local_geometry:{type:'corridor_envelope',centerline:lane.points,nominal_buffer_radius:lane.width/2,cap:'round',join:'round',cells,cell_mask_semantic:'CELL_CENTER_MASK_REFERENCE_FOR_CORRIDOR; minimum clear swept envelope is an additional design invariant'},coordinate_semantic:'世界 X/Z；Y 为方块底标高，ground_y 是最高地面方块的索引；现状行走顶面为 ground_y+1',height_or_section_baseline:{authority:'OBSERVED_SNAPSHOT',samples:profiles.find(p=>p.id===lane.id).samples,fields:profiles.find(p=>p.id===lane.id).fields,existing_surface_y_rule:'ground_y + 1',planning_design_surface:'逐地形肩部衔接；共同边缘以现状顶面±1格作为联合设计调节范围，不规定踏步构造',section_owner:'PUBLIC-COORDINATOR + affected household Builder'},nominal_width:lane.width,minimum_clear_requirement:{horizontal_blocks:lane.id==='LANE-01'?3:2,vertical_blocks:3,semantic:'连续可行走净宽；垂直净空自最终行走面起算。名义mask不可替代净宽/转弯验证；门扇、货物、檐柱、挡护均不得侵入',status:'PLANNING_REQUIREMENT_NOT_RUNTIME_CERTIFICATION'},adjustment_envelope:{centerline_fixed_for_this_handoff:true,ground_adjustment_blocks:[-1,1],shoulder_expansion:'仅公共所有方可在SPACE-01内做局部净宽补偿；不得进入P1/P2私院或其它未给出的地块；需记录新接口revision',household_rule:'户侧门前步级和停留均在本户apron解决，家庭 Builder 不拥有公共路工'},rights_access_semantic:'拟议共同通行地役；原权利人及使用共同体须同意，未经批准不声称既成公共权利',flow_or_service_semantic:lane.id==='LANE-01'?'西来首卸候选，驮畜/车辆未验证，不准自动把重货送入北门前':lane.id==='LANE-02'?'双向步行轻载；无整队驮畜、无候检堵塞':'跨两户连续步行通行，公共通行优先于收件停留',coordination_owner:'PUBLIC-COORDINATOR：MP-P04/PACKAGE-03 公共接口责任角色，实际承接人待Owner指派',resolve_before:'BEFORE_DESIGN_FREEZE',uncertainty:['局部落格后连续净宽、折点和步级需联合设计验证','公共所有方尚未接受本轮局部调节/责任分配；不是缺少几何坐标','通行权须在world write前确认']});}
interfaces.push({interface_id:'R2-IF-COMMON-EDGE',interface_revision:'r1',role:'北户—共同院关系',source_object:'SPACE-01',source_revision:'MP-P04-r1',status:'INHERITED_DESIGN_PROPOSAL',local_geometry:{type:'protected_common_space',polygon:src.shared_spaces[0].polygon,cells:mask(src.shared_spaces[0].polygon)},coordinate_semantic:boundary,nominal_width:null,minimum_clear_requirement:{rule:'共同院整体不属于家庭可建地；穿行按R2-IF-LANE-04/02保护，卸载不越过门前净空'},height_or_section_baseline:{ground_y_range:stats(mask(src.shared_spaces[0].polygon)).ground_y_range,per_column_ref:'evidence/地表采样.json',semantic:'现状缓坡分段使用，不设统一平台或假定水往某处自然排走'},adjustment_envelope:'本轮只定义北边接口；家庭Builder不得重设首卸/院内容量，公共协调方负责公共面局部适应',rights_access_semantic:'多共同体拟议共同使用；两户无圈占、收费封路或扩户权',flow_or_service_semantic:'西首卸、东轻载；开放空地承担等候与错峰，不是剩余可开发土地',coordination_owner:'PUBLIC-COORDINATOR',resolve_before:'BEFORE_DESIGN_FREEZE',uncertainty:['共同使用制度与维护责任待确认；公院施工不在两户BDP内']});
const spans=[[[754,1635],[758,1633.666667]],[[782,1632.571429],[785,1635.142857]]];
for(let i=0;i<2;i++){const p=parcels[i],cells=p.allocation.private_frontage_apron.cells;interfaces.push({interface_id:`R2-IF-THRESHOLD-${i+1}`,interface_revision:'r1',source_object:src.frontages[i].id,source_revision:'MP-P04-r1; R2-r1 internal refinement',role:i===0?'低肩收交与家庭门内停步':'上沿复核与短宿到达门内停步',status:'DESIGN_PROPOSAL',local_geometry:{type:'threshold_search_band',preferred_search_segment:spans[i],frontage_reference_line:p.frontage,cells,semantic:'segment为功能入口搜索位置，不是墙线或门洞；本户apron作为高差/停留缓冲'},coordinate_semantic:boundary,height_or_section_baseline:{per_column:cells.map(c=>[...c,ground.get(key(c))[3],ground.get(key(c))[3]+1]),fields:['x','z','observed_ground_block_y','observed_surface_y'],preferred_contact_surface_y:i===0?[131,132]:[136,136],rule:'最终门前接口行走面与PUBLIC-COORDINATOR共同冻结；户内消化余下高差，入口不得靠外伸楼梯吞路'},nominal_width:1.5,minimum_clear_requirement:{entry_blocks:1,public_through_blocks:2,semantic:'入口至少单人可达；公共连续净宽另行保持2，私侧停留不得站入路中'},adjustment_envelope:{horizontal:'入口可在本户apron内沿frontage调整；不跨地块；优先段可移至等价同户段并保留低肩修理/上沿复核关系',vertical:'公共接触点随已同意路面±1；户内适应形式由Builder设计'},rights_access_semantic:'apron属拟议户用地而非公共道路；来客仅获有限收交/短宿邀请，不能穿家庭小院；两户互不拥有对方通行权',flow_or_service_semantic:i===0?'手提修理件与住户进入；热/脏作业在户内控制':'少量候检、复核和短宿到达；完成复核者回到公共轻载线',coordination_owner:`BDP-0${i+1} + PUBLIC-COORDINATOR`,resolve_before:'BEFORE_DESIGN_FREEZE',uncertainty:['确切门、步级、层间通路与可居住功能由Builder证明']});}
write('interface-baselines.json',{revision:'r1',source_plan_revision:'MP-P05R2-r1',authority:'DESIGN_PROPOSAL',interfaces});
const services=[];
for(let i=1;i<=2;i++)for(const [type,label,when] of [['CLEAN_WATER','洁净水','BEFORE_PERMANENT_OCCUPATION'],['WASTE','污物收集','BEFORE_OPERATION'],['GOODS_FUEL','小批货物/燃料','BEFORE_OPERATION'],['RAINWATER','雨水边界','BEFORE_DESIGN_FREEZE']])services.push({service_id:`R2-S${i}-${type}`,service_type:type,status:'RESERVATION_WITH_EXTERNAL_HOLD',interface_location_or_ref:`interface-baselines.json#R2-IF-THRESHOLD-${i}`,upstream_or_downstream_owner:'PUBLIC-COORDINATOR 负责与 MP-P04 PACKAGE-03 公共服务及其已声明的MP-P03日需协调方对接；本轮未读取MP-P03包',builder_responsibility:'RESERVE_INTERFACE_ONLY',neighbor_or_public_responsibility:type==='RAINWATER'?'确认允许受纳点/路面边界控制标高、污染隔离和下游责任后，才可冻结跨界排水；无可用公共排水设施事实':type==='CLEAN_WATER'?'确认水源、送达来向、供水节奏/水质与持续能力；现有父包没有已闭合的供水承诺':'确认转运终端、时间和责任；不得由家庭Builder发明场外终端',local_requirement:type==='CLEAN_WATER'?'户内保留洁净接收和日需小储备空间；不得因裸岩推断地下水，也不预定打井坐标':type==='WASTE'?'户内封闭暂存、按批带出；洁净收水和污物搬出不同时间，不宣称东口天然洁污分离':type==='RAINWATER'?'保留户内收集/调蓄与可接续能力；公共通行面不得作为默认排放终点，未闭合前不得设计越界出水管':'仅手提批次送至门内apron；较重来货在公共首卸卸下，不在LANE-04长期存放',allowed_local_adjustment:'本户apron内移动预留，保持洁污隔离和门前净空；跨界改点需接口revision',resolve_before:when,uncertainty:type==='RAINWATER'?'跨界雨水受纳点与责任尚未被公共方冻结，因此两户保持CONCEPT_DESIGN_READY':'许可/供给/清运尚未证实；预留位置已本地化，运行承诺不因此成立',label});
write('external-service-interfaces.json',{revision:'r1',services,temporal_protocol:{authority:'DESIGN_PROPOSAL',sequence:['通行持续优先；到货按小批首卸','洁净水/食品先接收，移入户内','货物与复核分批，不占路排队','污物在无洁净接收时段封闭转运；清理后恢复'],peak_response:'溢出时暂停收件/短宿接纳，由公共协调方调度；不启用未给出的替代路或私占院地'}});
const uncertainties=[{id:'U-PUBLIC',state:'UNRESOLVED',resolve_before:'BEFORE_DESIGN_FREEZE',owner:'PUBLIC-COORDINATOR',question:'接受局部路带、净宽要求、门前接触标高和跨界雨水责任',minimum_closure:'回签interface revision及服务受纳位置；如变更，仅重发受影响接口与BDP',does_not_block:'两户在所给包络内概念设计'},{id:'U-HABITABILITY',state:'TO_BE_DESIGNED',resolve_before:'BEFORE_DESIGN_FREEZE',owner:'minecraft-builder',question:'证明两户各自完整生活、储备/卫生、入口及P02短宿可共存',minimum_closure:'实际Plan/Section/Sequence功能净尺度和通行证据；不可用总地块面积代替',does_not_block:'包络内Architecture Design探索'},{id:'U-GROUND',state:'PARTIAL_EVIDENCE',resolve_before:'BEFORE_DESIGN_FREEZE',owner:'minecraft-builder with read-only site evidence',question:'具体基础/切挖影响与深部既有内容兼容',minimum_closure:'沿具体设计影响体积核验；已知深部位置保持不触及，禁止借本轮浅层无空气推定深部可改'},{id:'U-TITLE',state:'UNRESOLVED',resolve_before:'BEFORE_WORLD_WRITE',owner:'Owner + original rights holders',question:'户用地、公共地役、现场既有内容保护的实际许可',minimum_closure:'目标/revision/hash绑定授权；不修改Canon解决许可'},{id:'U-SUPPLY',state:'UNRESOLVED',resolve_before:'BEFORE_PERMANENT_OCCUPATION',owner:'PUBLIC-COORDINATOR + household operators',question:'外部日需与洁净水能力/稳定性',minimum_closure:'实际来源、批次、储备与中断应对；不默认从任何方向已供应'},{id:'U-OPERATION',state:'UNRESOLVED',resolve_before:'BEFORE_OPERATION',owner:'PUBLIC-COORDINATOR + household operators',question:'错峰洁污、轻载通行及废物终端',minimum_closure:'服务时段/责任与有效通达验证；无运行数据时不得承诺吞吐量'}];
const protocol={report_fields:['package/interface IDs and revisions','conflicting relation or missing information','observed evidence','bounded adaptation attempted','why insufficient','minimum upstream change','affected downstream packages'],adapt_first:['户内移动入口与小院','顺坡分段或垂直组织','错时复核/收件且不删家庭功能'],escalate_when:['两户完整生活与通行经局部适应仍不能共存','共同接口或深部保护与相称工程冲突','日需/权属方案无法闭合'],forbidden_silent_changes:['扩地/扩户','删除短宿或家庭程序','圈占共同院','关闭LANE-04或东口','发明公共管线或终端'],revision_rule:'最小对象修订；变更接口时递增revision，相关下游设计置STALE_FOR_FIDELITY_REVIEW；不覆写MP-P04'};
const bdp=parcels.map((p,i)=>({package_id:`BDP-0${i+1}`,package_revision:'r1',recipient:'minecraft-builder',scope:{plan:'MP-P05R2',parcel_id:p.id,source_package:'MP-P04/PACKAGE-01',households:1},scale:'URBAN_ENSEMBLE',builder_handoff_readiness:'CONCEPT_DESIGN_READY',readiness_reason:'本地地块、公共通路、门前与保护语义可解析，可开始Architecture Design；跨界雨水受纳和公共协同标高未闭合，不能冻结设计。此状态不是回归评判。',why:i===0?'在西来货物转为轻载之前就近小修理与值守，家庭小院退到户内低肩，避免与公共横通争地':'在上沿轻载出口附近复核并提供有限短宿，浅地块保留家庭生活而不变成公院客栈',design_context:pctx,planning_causal_context:{rights:'拟议家庭用地；公院/通行地役仍属共同协调，两户没有圈占权',flow:i===0?'西首卸→手提入低肩收件→小修理→交还公院/向东轻载':'公院轻载→上段复核门内停步→完成后回东口；短宿访客不穿家庭院',rhythm:'批次来货/日常家庭；洁净接收与污物带出错时',stock:'户内少量工具、日需、在手一批物品；不重复计算公共储备',externalities:'作业、等待、滴水不得挤占路带或家庭生活；热烟控制不凭空升级大型产业',terrain:p.statistics,growth_stage:'R2-G2；R2-G3有限短宿为假设，不是实存历史',neighbor_relation:'两户以公共LANE-04联系，各自小院独立；不发明跨户后巷或共墙'},upstream_anchors_flows:['SPACE-01西首卸/共同交割','LANE-04连续北前沿步行','LANE-02东轻载'],spatial_envelope:{polygon:p.polygon,cells:p.cells,private_open_yard:p.allocation.private_open_yard,private_frontage_apron:p.allocation.private_frontage_apron,architectural_search_mask:p.allocation.architectural_search_mask},boundary_semantic:boundary,required_adjacency:['户内家庭小院独立可达','面向对应门前搜索段','不跨户连通小院'],required_access:[`R2-IF-THRESHOLD-${i+1}`,'R2-IF-LANE-04','R2-IF-LANE-02'],shared_space_service_relations:'共同院与路带只引用不计入户用建筑容量；外部服务按直接服务文件预留并HOLD',program_requirements:read('planning-data.json').programs[i],historical_growth_stage:'EARLY_GROWTH / PLANNING_ASSUMPTION; not implementation chronology',architecture_kit_requirements:read('planning-data.json').architecture_kit_requirements,planner_fixed:['一完整家庭/户；两户总量不增','保持修理低肩/复核上沿的流动关系','公共通路和共同院不能转为门廊、楼梯、长时堆货或排队区','家庭小院与门前缓冲保留，可在等价同户范围适应','不擅改地下现状','所有服务越界必须由公共责任方闭合'],builder_adaptable:['exact footprint within search mask, with equivalent yard/apron rearrangement inside parcel','rooms, floor count, plan/section/sequence','structure, foundation after influence-volume evidence','roof, facade, openings, palette','local steps, retaining, rainwater collection after interface closure'],interface_baselines:interfaces.filter(q=>!q.interface_id.startsWith('R2-IF-THRESHOLD-')||q.interface_id===`R2-IF-THRESHOLD-${i+1}`),external_service_interfaces:services.filter(q=>q.service_id.startsWith(`R2-S${i+1}-`)),dependencies:[{file:'interface-baselines.json',revision:'r1',sha256:hash('interface-baselines.json')},{file:'external-service-interfaces.json',revision:'r1',sha256:hash('external-service-interfaces.json')},{file:'evidence/地表采样.json',sha256:hash('evidence/地表采样.json')},{file:'evidence/浅层采样.json',sha256:hash('evidence/浅层采样.json')}],known_uncertainty:uncertainties,upstream_issue_protocol:protocol,source_refs:['provenance.json','sources/来源登记.json'],world_write_authorization:false}));
write('builder-design-packages.json',{plan_id:'MP-P05R2',revision:'r1',contract_version:'1.0',packages:bdp,read_order:'读取目标package即含全部当前因果/接口；只需直接文件核对事实。不要求回读任何完整父规划、其它BDP或被禁止目录。'});
write('handoff-register.json',{source_plan_revision:'r1',review_status:'AWAITING_GPT_AND_OWNER_REVIEW',regression_verdict:null,uncertainties,upstream_issue_protocol:protocol,public_coordination:{id:'PUBLIC-COORDINATOR',assignment:'PROPOSED_ROLE_NOT_ACTUAL_APPOINTMENT',scope:'只协调直接公共接口，不在本轮重规划PACKAGE-03其它用地/建筑',approval:'由Owner指派/确认；不是本轮构造出的既有机构'},deep_existing_content:{source:'evidence/浅层采样.json block_entities',items:near.block_entities.filter(c=>c.x>=775&&c.x<=785&&c.z>=1625&&c.z<=1637),meaning:'深处有实体位置证据，不能把地表无建筑解读成地下无人造内容；不读库存、不改结构'},world_writes:0});
console.log(JSON.stringify({parcels:parcels.map(p=>({id:p.id,...p.statistics,yard:p.allocation.private_open_yard.area,apron:p.allocation.private_frontage_apron.area,search:p.allocation.architectural_search_mask.area})),interfaces:interfaces.length,services:services.length,packages:bdp.length}));
