"""模型明确选择的解释与 verdict；代码仅装配已选择文本和可追溯机器事实。"""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
def read(name):return json.loads((ROOT/'profile'/name).read_text(encoding='utf-8'))
s=read('regional-summary.json');t=read('terrain-profile.json');stats=s['statistics'];whole=stats['whole_group'];west=stats['west'];east=stats['east']
old=json.loads((ROOT.parent/'WB-002R/profile/owner-hypothesis-evaluation.json').read_text(encoding='utf-8'))
items=[
{'id':'H-01','owner_observation':'温带 / 枯树环境为主，非高密热带雨林','machine_observation':{'biomes':whole['biomes'],'vegetation':whole['vegetation']},'derived_evidence':['biome-profile.json','vegetation-profile.json'],'interpretation':'稀疏叶冠和非雨林环境有支持；hot_shrubland、savanna、arid_highlands 等不支持把整区直接称作温带。log 与少量干地植被不证明枯树占优，枯树仍为 Owner 视觉解释。','verdict':'PARTIALLY_SUPPORTED'},
{'id':'H-02','owner_observation':'多山少平原','machine_observation':{'whole_flat_share':whole['flat_share'],'whole_gentle_share':whole['gentle_share'],'east_area_share':east['area_blocks2']/whole['area_blocks2'],'east_elevation':east['elevation'],'east_relief32':east['relief32'],'east_flat_share':east['flat_share']},'derived_evidence':['terrain-profile.json','low-relief-components.jsonl'],'interpretation':'完整范围由高起伏东部主体占主导，平地只占约五分之一；东岛平地约6%。支持整体印象，但山地不等于某个 biome，平地是操作性形态而非土地用途。旧低岛局部 NOT_SUPPORTED 不适用于全域。','verdict':'SUPPORTED'},
{'id':'H-03','owner_observation':'总体西低东高','machine_observation':{'pearson':t['pearson_x_elevation'],'OLS_Y_per_100_X':t['OLS_Y_per_100_X'],'west_elevation':west['elevation'],'east_elevation':east['elevation'],'longitude_bands':t['longitude_bands']},'derived_evidence':['terrain-profile.json'],'interpretation':'完整范围显著正相关，西岛与东岛中位高程相差83格；经度带仍有东岸下降、局部低地与高峰，不能解释为每一步都升高或因果推断。','verdict':'SUPPORTED'},
{'id':'H-04','owner_observation':'平原主要集中在西侧两个岛屿 / 岛片','machine_observation':{'west_share_of_all_flat_columns':west['area_blocks2']*west['flat_share']/(whole['area_blocks2']*whole['flat_share']),'west_flat_share':west['flat_share'],'east_flat_share':east['flat_share'],'west_component':s['west_component'],'east_component':s['east_component']},'derived_evidence':['land-components.json','low-relief-components.jsonl','water-topology.json','../../WB-002R/profile/topology-witnesses.json'],'interpretation':'平地主要集中在西部有强支持。西侧 C 形两翼属于同一岛；中部看似另岛的低地通过陆颈连接东部主岛，是其西伸部分。不能将 Owner 两个空间印象直接转成两个独立低岛，原视点仍未精确定位。','verdict':'PARTIALLY_SUPPORTED'},
{'id':'H-05','owner_observation':'可自然分成三个潜在部族区域','machine_observation':{'alternatives':read('zoning-alternatives.json'),'decision':read('zoning-decision.json')},'derived_evidence':['zoning-alternatives.json','zoning-decision.json','natural-zones.jsonl'],'interpretation':'完整范围存在强烈自然差异，三种景观层次可作为讨论假说；k3 主要增加坡麓/岸缘过渡带，并未证明恰好三个稳定且紧凑的自然区。保留两大水陆边界明确的研究参考单元和内部连续梯度。未创建部族或政治实体。','verdict':'INSUFFICIENT'}]
for item in items:item['scope']={'bounds':s['bounds'],'population':'all dry land in complete study rectangle, including satellite components','scope_status':s['scope_status']}
(ROOT/'profile/owner-hypothesis-evaluation.json').write_text(json.dumps({'status':'RESEARCH_ONLY / NOT_WORLD_CANON','predecessor_local_evaluation':old,'whole_scope_evaluation':items},ensure_ascii=False,sort_keys=True,indent=2)+'\n',encoding='utf-8')
