import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {fileURLToPath} from 'node:url';
import {execute,worldStatus} from '../AI-Offline/L3_外交层/离线执行接口.mjs';import {RegionReader,readNBT} from '../AI-Offline/L3_外交层/存档读取接口.mjs';import {blueprintPhase} from '../AI-Offline/L3_外交层/蓝图执行接口.mjs';
const R=path.dirname(fileURLToPath(import.meta.url)),world='D:/Games/Minecraft/.minecraft/versions/MB-V110-T12-隔离实例/saves/MB-V110-T12-京町家修复',s=process.argv[2],src='D:/Games/Minecraft/.minecraft/versions/26.2-Fabric 0.19.5/saves/MB-V19-T11-京町家';
const write=(n,v)=>fs.writeFileSync(R+'/证据/'+n,JSON.stringify(v,(_,x)=>typeof x==='bigint'?String(x):x,2));
function identity(){if(fs.realpathSync(world)!==path.resolve(world))throw Error('WORLD_PATH');const d=readNBT(fs.readFileSync(world+'/level.dat')).Data,g=readNBT(fs.readFileSync(world+'/data/minecraft/world_gen_settings.dat')).data;if(d.LevelName!=='MB-V110-T12-京町家修复'||g.generate_structures!==0||g.dimensions['minecraft:overworld'].generator.type!=='minecraft:flat')throw Error('WORLD_IDENTITY_BLOCKER');return{world,name:d.LevelName,version:d.Version,generation:g};}
function sourceUnchanged(){const h=JSON.parse(fs.readFileSync(R+'/证据/来源世界文件哈希.json'));for(const[f,v]of Object.entries(h))if(crypto.createHash('sha256').update(fs.readFileSync(src+'/'+f)).digest('hex')!==v)throw Error('SOURCE_CHANGED:'+f);}
identity();sourceUnchanged();await worldStatus(world);if(!/^(baseline|reload|[0-9][0-9]-[A-Za-z]+)$/.test(s)||fs.existsSync(R+'/证据/'+s+'-实存.json'))throw Error('STAGE_EXISTS_OR_INVALID');
if(s!=='baseline'){const phases=[];if(s!=='reload'){const m=JSON.parse(fs.readFileSync(R+'/蓝图/'+s+'/清单.json'));for(const f of m.files){const p=blueprintPhase(JSON.parse(fs.readFileSync(R+'/蓝图/'+s+'/'+f)));phases.push({palette:p.palette,operations:p.operations});}}write(s+'-执行.json',await execute({world_path:world,phases}));}
const rr=new RegionReader(world),palette=[],ids=new Map(),buffer=Buffer.alloc(56*96*36*2);let i=0;for(let y=10;y<46;y++)for(let z=0;z<96;z++)for(let x=0;x<56;x++){const v=rr.get(x,y,z)??'UNGENERATED';if(!ids.has(v)){ids.set(v,palette.length);palette.push(v);}buffer.writeUInt16LE(ids.get(v),i++*2);}fs.writeFileSync(R+'/证据/'+s+'.u16',buffer);write(s+'-实存.json',{...identity(),origin:[0,10,0],shape_yzx:[36,96,56],palette,sha256:crypto.createHash('sha256').update(buffer).digest('hex')});sourceUnchanged();write(s+'-来源保护.json',{source_world_unchanged:true,source_world:src});console.log(s+' saved snapshot; source unchanged');
