import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {fileURLToPath} from 'node:url';
import {execute,worldStatus} from '../AI-Offline/L3_外交层/离线执行接口.mjs';import {readNBT,RegionReader} from '../AI-Offline/L3_外交层/存档读取接口.mjs';import {blueprintPhase} from '../AI-Offline/L3_外交层/蓝图执行接口.mjs';
const R=path.dirname(fileURLToPath(import.meta.url)),world=R+'/实例/saves/MB-V18-T10-罗马浴场精修',source='D:/Games/Minecraft/.minecraft/versions/26.2-Fabric 0.19.5/saves/MB-V17-T09-罗马浴场',stage=process.argv[2],stages=['01-Functional','02-Architectural','03-Material','04-Composition','05-Restraint','reload'];
const hash=b=>crypto.createHash('sha256').update(b).digest('hex'),write=(n,v)=>fs.writeFileSync(R+'/证据/'+n,JSON.stringify(v,(_,x)=>typeof x==='bigint'?String(x):x,2));
function sourceCheck(){const baseline=JSON.parse(fs.readFileSync(R+'/证据/来源文件基准.json'));for(const [p,h] of Object.entries(baseline))if(hash(fs.readFileSync(source+'/'+p))!==h)throw Error('SOURCE_CHANGED '+p);return{source_unchanged:true,files:Object.keys(baseline).length};}
function identity(){if(fs.realpathSync(world)!==path.resolve(world))throw Error('TARGET_PATH');const d=readNBT(fs.readFileSync(world+'/level.dat')).Data,g=readNBT(fs.readFileSync(world+'/data/minecraft/world_gen_settings.dat')).data;if(d.LevelName!=='MB-V18-T10-罗马浴场精修'||g.generate_structures!==0||g.dimensions['minecraft:overworld'].generator.type!=='minecraft:flat')throw Error('TARGET_IDENTITY');return{name:d.LevelName,world,version:d.Version,structures:g.generate_structures};}
if(!stages.includes(stage))throw Error('STAGE');if(fs.existsSync(R+'/证据/'+stage+'-执行.json'))throw Error('ALREADY_EXECUTED');const idx=stages.indexOf(stage);if(idx>0&&!fs.existsSync(R+'/证据/'+stages[idx-1]+'-执行.json'))throw Error('PRIOR_STAGE_MISSING');identity();sourceCheck();await worldStatus(world);
const phases=[];if(stage!=='reload'){const list=JSON.parse(fs.readFileSync(R+'/蓝图/'+stage+'/清单.json'));for(const file of list.files){const b=JSON.parse(fs.readFileSync(R+'/蓝图/'+stage+'/'+file)),p=blueprintPhase(b);phases.push({palette:p.palette,operations:p.operations});}}
const result=await execute({world_path:world,phases});write(stage+'-执行.json',result);
const rr=new RegionReader(world),palette=[],ids=new Map(),b=Buffer.alloc(56*144*144*2);let i=0;for(let y=10;y<66;y++)for(let z=0;z<144;z++)for(let x=0;x<144;x++){const s=rr.get(x,y,z)??'UNGENERATED';if(!ids.has(s)){ids.set(s,palette.length);palette.push(s);}b.writeUInt16LE(ids.get(s),i++*2);}
fs.writeFileSync(R+'/证据/'+stage+'.u16',b);write(stage+'-实存.json',{...identity(),...sourceCheck(),origin:[0,10,0],shape_yzx:[56,144,144],palette,sha256:hash(b),source:'RegionReader after formal save/shutdown'});console.log(stage+' saved, sampled; T09 unchanged');
