/* 启动与 DOM 适配处于工程外围；通过 L3 接口编辑，不触碰世界文件。 */
(async function(){'use strict';const $=id=>document.getElementById(id),base=window.TERRITORY_BASE,api=createTerritoryEditor(base),cats=api.categories,canvas=$('map'),ctx=canvas.getContext('2d');window.editor=api;
const raster=document.createElement('canvas');raster.width=base.width;raster.height=base.height;const rc=raster.getContext('2d');let scale=1,ox=0,oz=0,drag=null,dirty=false,qaRevision=-1;
const outlines={};for(const name of ['commons','connector']){const mask=new Set();for(const [z,a,b] of base[name])for(let x=a;x<=b;x++)mask.add((z-base.bounds[1])*base.width+x-base.bounds[0]);const p=new Path2D();for(const i of mask){const x=i%base.width,z=Math.floor(i/base.width);if(!mask.has(i-base.width)){p.moveTo(x,z);p.lineTo(x+1,z);}if(!mask.has(i+base.width)){p.moveTo(x,z+1);p.lineTo(x+1,z+1);}if(x===0||!mask.has(i-1)){p.moveTo(x,z);p.lineTo(x,z+1);}if(x===base.width-1||!mask.has(i+1)){p.moveTo(x+1,z);p.lineTo(x+1,z+1);}}outlines[name]=p;}
const plain=document.createElement('canvas');plain.width=base.width;plain.height=base.height;const pc=plain.getContext('2d'),pd=pc.createImageData(base.width,base.height),initial=api.view().values;for(let i=0;i<initial.length;i++)if(initial[i]!==255)pd.data.set([140,160,150,255],i*4);pc.putImageData(pd,0,0);
const images={};for(const name of ['terrain','biome']){const im=new Image();im.src=base[name+'Image'];await im.decode();images[name]=im;}
for(const [i,c] of cats.entries()){$('category').add(new Option(c.name,i));const l=document.createElement('label');l.innerHTML=`<input type="checkbox" ${i===0||i===2?'checked':''}> <span class="swatch" style="background:${c.color}"></span>${c.name}`;l.querySelector('input').onchange=e=>api.lock(i,e.target.checked);$('locks').append(l);}$('category').value='1';for(const v of Object.values(base.biomeLegend)){const d=document.createElement('div');d.innerHTML=`<span class="swatch" style="background:rgb(${v.color})"></span>${v.name}`;$('legend').append(d);}
function status(t){$('message').textContent=t;}function refresh(){const view=api.view(),pixels=rc.createImageData(base.width,base.height),rgb=cats.map(c=>c.color.match(/\w\w/g).map(x=>parseInt(x,16)));for(let i=0;i<view.values.length;i++){const c=view.values[i];if(c!==255){pixels.data.set([...rgb[c],255],i*4);}}rc.putImageData(pixels,0,0);draw();}
function accepted(runs,color){ctx.fillStyle=color;for(const [z,a,b] of runs)ctx.fillRect(ox+(a-base.bounds[0])*scale,oz+(z-base.bounds[1])*scale,(b-a+1)*scale,Math.max(scale,0.6));}
function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.imageSmoothingEnabled=false;const mode=$('base').value;if(images[mode])ctx.drawImage(images[mode],ox,oz,base.width*scale,base.height*scale);else{ctx.drawImage(plain,ox,oz,base.width*scale,base.height*scale);}if($('territory').checked){ctx.globalAlpha=+$('opacity').value;ctx.drawImage(raster,ox,oz,base.width*scale,base.height*scale);ctx.globalAlpha=1;}ctx.globalAlpha=0.22;if($('commons').checked)accepted(base.commons,'#fff1a3');if($('connector').checked)accepted(base.connector,'#edbbff');ctx.globalAlpha=1;ctx.save();ctx.translate(ox,oz);ctx.scale(scale,scale);ctx.lineWidth=2/scale;for(const name of ['commons','connector'])if($(name).checked){ctx.strokeStyle=name==='commons'?'#ffe477':'#d5a5ff';ctx.stroke(outlines[name]);}ctx.restore();if(drag?.mode==='rect'){ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.strokeRect(ox+(Math.min(drag.start.x,drag.last.x)-base.bounds[0])*scale,oz+(Math.min(drag.start.z,drag.last.z)-base.bounds[1])*scale,(Math.abs(drag.last.x-drag.start.x)+1)*scale,(Math.abs(drag.last.z-drag.start.z)+1)*scale);}}
function fit(){scale=Math.min(canvas.width/base.width,canvas.height/base.height);ox=(canvas.width-base.width*scale)/2;oz=(canvas.height-base.height*scale)/2;draw();}new ResizeObserver(()=>{canvas.width=canvas.clientWidth;canvas.height=canvas.clientHeight;fit();}).observe(canvas);
function point(e){const r=canvas.getBoundingClientRect(),px=e.clientX-r.left,py=e.clientY-r.top;return {px,py,x:Math.floor((px-ox)/scale)+base.bounds[0],z:Math.floor((py-oz)/scale)+base.bounds[1]};}function changed(){dirty=true;qaRevision=-1;$('ack').checked=false;$('stats').classList.add('warning');status('草稿已修改；QA 待更新。请保存以免关闭后丢失。');refresh();}
canvas.onpointerdown=e=>{if(drag||e.button>1)return;const p=point(e),mode=e.button===1?'pan':$('mode').value;drag={mode,start:p,last:p};canvas.setPointerCapture(e.pointerId);if(mode!=='pan'){api.begin(mode==='erase'?4:+$('category').value);if(mode!=='rect')api.brush(p.x,p.z,Math.max(1,Math.min(128,+$('radius').value||1)));}draw();};canvas.onpointermove=e=>{const p=point(e),c=api.at(p.x,p.z);$('position').textContent=`X ${p.x} / Z ${p.z} · ${c===255?'水域/范围外':cats[c].name} · ${scale.toFixed(2)}×`;if(!drag)return;const prev=drag.last;if(drag.mode==='pan'){ox+=p.px-prev.px;oz+=p.py-prev.py;}else if(drag.mode!=='rect'){const n=Math.max(Math.abs(p.x-prev.x),Math.abs(p.z-prev.z));for(let k=1;k<=n;k++)api.brush(Math.round(prev.x+(p.x-prev.x)*k/n),Math.round(prev.z+(p.z-prev.z)*k/n),Math.max(1,Math.min(128,+$('radius').value||1)));}drag.last=p;draw();};function finish(){if(!drag)return;if(drag.mode!=='pan'){if(drag.mode==='rect')api.rectangle(drag.start.x,drag.start.z,drag.last.x,drag.last.z);if(api.end())changed();}drag=null;draw();}canvas.onpointerup=finish;canvas.onpointercancel=finish;
canvas.onwheel=e=>{e.preventDefault();const p=point(e),old=scale;scale=Math.max(0.08,Math.min(32,scale*Math.exp(-e.deltaY*0.001)));ox=p.px-(p.px-ox)*scale/old;oz=p.py-(p.py-oz)*scale/old;draw();};function zoom(s){const old=scale;scale=s;ox=canvas.width/2-(canvas.width/2-ox)*s/old;oz=canvas.height/2-(canvas.height/2-oz)*s/old;draw();}$('fit').onclick=fit;$('one').onclick=()=>zoom(1);$('detail').onclick=()=>zoom(8);for(const id of ['base','territory','opacity','commons','connector'])$(id).oninput=draw;
for(const id of ['undo','redo'])$(id).onclick=()=>{if(api[id]())changed();};document.onkeydown=e=>{if(e.ctrlKey&&e.key.toLowerCase()==='z'&&!['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName)){e.preventDefault();if(api[e.shiftKey?'redo':'undo']())changed();}};
async function qa(){if(drag)throw Error('请先结束笔画');status('正在计算完整逐格 QA…');await new Promise(r=>setTimeout(r,30));const q=api.qa();qaRevision=q.revision;$('stats').classList.remove('warning');$('stats').innerHTML=`<p class="warning">未分配 ${q.unassigned.toLocaleString()} · 争议 ${q.disputed.toLocaleString()}<br>accepted 改动 ${q.acceptedChanged}</p><table><tr><th>类别</th><th>面积 / 连通片</th></tr>`+cats.map((c,i)=>`<tr><td>${c.name}</td><td>${q.areas[i].toLocaleString()} / ${q.fragmentation[i].components}</td></tr>`).join('')+'</table><p>'+q.fragmentation.map((f,i)=>`${cats[i].name}：碎片 ${f.smallComponents} / 飞地候选 ${f.enclaveCandidates}`).join('<br>')+'</p><details><summary>接壤单位边数</summary>'+cats.flatMap((c,i)=>cats.slice(i+1).map((d,k)=>`${c.name} ↔ ${d.name}: ${q.adjacency[i][i+k+1]}`)).join('<br>')+'</details>';status('QA 已更新。飞地 / 碎片是几何提示，需 Owner 判断。');return q;}$('qa').onclick=qa;
function download(blob,name){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);} $('save').onclick=()=>{download(new Blob([JSON.stringify(api.document())],{type:'application/json'}),'territory-draft.json');dirty=false;};$('load').onchange=async e=>{try{const file=e.target.files[0];if(file.size>50*1024*1024)throw Error('文件超过 50 MiB');api.load(JSON.parse(await file.text()));changed();}catch(err){status('载入失败：'+err.message);}e.target.value='';};
async function bundle(formal){try{if(drag)throw Error('请先结束笔画');if(formal&&(!$('ack').checked||!$('owner').value.trim()||qaRevision!==api.view().revision))throw Error('请先更新 QA、填写 Owner 并勾选确认');await qa();if(formal&&(!$('ack').checked||qaRevision!==api.view().revision))throw Error('状态已改变，请重新确认');const revision=api.view().revision;const png=await new Promise(r=>raster.toBlob(r,'image/png')),blob=api.bundle(formal?'OWNER_CONFIRMED':'DRAFT',formal?$('owner').value.trim():null,new Uint8Array(await png.arrayBuffer()));if(drag||api.view().revision!==revision)throw Error('导出时发生编辑，请重试');download(blob,'territories-'+(formal?'confirmed':'draft')+'.zip');dirty=false;status('导出完成；请解压到目标目录并交独立审核。');}catch(err){status(err.message);}}$('export').onclick=()=>bundle(false);$('confirm').onclick=()=>bundle(true);window.onbeforeunload=e=>{if(dirty){e.preventDefault();e.returnValue='';}};refresh();fit();await qa();
})();
