"""把本轮显式规划判断整理为轻量交接对象；仅写 MP-P01，不更改 Canon 或已有规划。"""
from pathlib import Path
import json,hashlib,subprocess,html
R=Path(__file__).resolve().parent;repo=R.parents[1];g=R.parent/'建筑师/research';G=g;SRC=g/'human-geography/southern-island/WB-002R-R1'
def save(n,v):p=R/n;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(v,ensure_ascii=False,indent=2),encoding='utf8')
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
plan=json.loads((R/'planning-objects.json').read_text(encoding='utf8'))
regions=[{'id':'REGION-01','name':'西域低岛生产网络','authority':'DESIGN_PROPOSAL','canon_basis':'西域低岛人口、农牧与市场方向','geometry':{'type':'source_reference','mask':'R1 land_component == 1','semantic':'自然岛形作为上层研究覆盖，不是本轮新定地籍'},'hierarchy':['SETTLEMENT-01','SETTLEMENT-02','SETTLEMENT-03'],'formation':'连续低平地支持分散生产；集市和接驳分别集中，不能把岛全涂成住宅或农田。','expansion':'先填现有服务关系空缺；保留连片生产地与步行到达，边界由地权和水供应决定。'},
{'id':'REGION-02','name':'中域坡麓与转换网络','authority':'DESIGN_PROPOSAL','canon_basis':'东岛西侧低地/坡麓及Commons东connector','geometry':{'type':'source_reference','mask':'东岛西部低地/坡麓，精确中东界未定','not_polygon':True},'hierarchy':['SETTLEMENT-05'],'formation':'跨水、低陆运与山地驮运的转换成本叠加；不是任意港口圈。','expansion':'沿可用台地和货运接口断续增长；保留公地独立通达，不把贸易垄断变成领土吞并。'},
{'id':'REGION-03','name':'东域山地共同体网络','authority':'DESIGN_PROPOSAL','canon_basis':'富矿为 CANON_AUTHORED_RESOURCE；具体矿口未定','geometry':{'type':'source_reference','mask':'东岛山地核心；不使用NGEO-032的粗边界作为政治边界'},'hierarchy':['SETTLEMENT-06','SETTLEMENT-07','SETTLEMENT-08','SETTLEMENT-09'],'formation':'多点氏族/共同体与矿地服务保持分散；主峰构成交通阻力而不是首都位置。','expansion':'水粮燃料和安全出入先成立，再纳入季节生产点；不铺满脊线，不默认统一矿业城市。'}]
plan['regions']=regions
assumptions=[{'id':'A-TRANSPORT','authority':'PLANNING_ASSUMPTION','statement':'成熟前现代小规模驮运、近岸季节渡运可作为待核实方案；没有证据支持连续重车道或全年安全海运。','impact':'HIGH','branches':[{'id':'BRANCH-A','condition':'岸端/水深/近岸可航与装卸稳定得到下层证据','consequence':'保留03→05商业直达和03→04议事分流；09达到批量货流后可升级绕岛海运接口'}, {'id':'BRANCH-B','condition':'近岸仅季节可用或南岸不可航','consequence':'09不建常年外运中心；07/08缩为自给较强的地方与季节节点；粮食和成品分批储备，不承诺区域重货通路'}]},
{'id':'A-WATER','authority':'PLANNING_ASSUMPTION','statement':'低岛有可建立的分散淡水供应，但当前未验证可持续供水与农牧产量。','impact':'HIGH','branches':[{'condition':'供水足以支撑农牧丰余','consequence':'01维持主要居民/粮食集散；02补充分区集市'}, {'condition':'淡水严重不足','consequence':'西域转向低密牧用/耐旱生产与有限市场；缩小联盟远端专业人口，不用人工假设粮食过剩补洞'}]},
{'id':'A-MATURITY','authority':'PLANNING_ASSUMPTION','statement':'构想一个已稳定协商但空间仍渐进增长的联盟；具体年代/人口/敌国不编成Canon。','impact':'MEDIUM','sensitivity':'交换规模低时服务嵌入家庭/共同体，不同时建设九座城。'},
{'id':'A-TENURE','authority':'PLANNING_ASSUMPTION','statement':'Canon地方自治下，农业地权与矿山权属保持地方解释；不预设全国统一私有地块制。','impact':'MEDIUM','sensitivity':'家族、庄园或共有制度改变下层密度与空间占用，本轮不画parcel。'},
{'id':'A-SNAPSHOT','authority':'PLANNING_ASSUMPTION','statement':'接受既有自然调查作为本轮L0基线；未比对当前世界区域文件，不声称实时新鲜。','impact':'MEDIUM','sensitivity':'因大型地形变更而改变两岛或岸线时，受影响路线/节点全部回退SCOPED；下钻前须做最新现场核实。'}]
plan['assumptions']=assumptions
demands=[]
data=[('01','ANCHOR / CORE','长期食物与风险储备','家庭、牧者、山地购买者','REGIONAL','收获季集中、日常分散','01/02生产腹地→03/05→06','清洁水/土壤/养分与共享储备，地面不能全部城市化','GROWTH-01','01/02市场功能，可先户内与共同储存'),('02','ANCHOR / CORE','矿业与石工的可持续专业化','山地共同体和工匠','REGIONAL_CONDITIONAL','周期生产、季节运出','实际矿口→06/07/08→05/09','原矿/废石就近分选；燃料消耗、矿水、烟尘与居民清水分离','GROWTH-02','山地服务节点而非预先固定矿城'),('03','ESSENTIAL_SUPPORT','减轻转运等待与损耗','船户、驮队、货主、旅人','REGIONAL','多批次、天气窗口','03与05、05与06','牲畜/待运货不堵公众抵达；不由政治公地强收过境','GROWTH-02','转换中心内共享装卸/交易功能，规模大再独立'),('04','ANCHOR / CORE','跨域公正协商与共同动员','三席代表、地方共同体','STRATEGIC','定期议事/紧急动员','03→04与05→04','议事与公众到达不被货运堆场占满','GROWTH-03','共同治理场所，不等于全联盟最大居住中心'),('05','ORDINARY_DAILY','远端日常生活和救助','各共同体居民、伤病者','LOCAL','每日','07/08地方腹地','水源优先于生产；魔法医疗不能替代粮水和出入','GROWTH-01','本地混合居住/维修/互助可嵌入，无九套完整设施清单'),('06','ESSENTIAL_SUPPORT','燃料木材与土地维护','矿业、工匠、农牧户','REGIONAL','季节采集和轮作','经核实林灌地→生产节点','植被不等于可持续材积；采伐/坡面侵蚀/火灾风险限制吞吐','GROWTH-02','共同管理与间歇生产空间，禁止默认清山供炉'),('07','SPECIALIZED','信息、防御和共同祭誓','地方武装、信使、仪式参与者','STRATEGIC_EPISODIC','日常低量/事件高峰','地方节点↔04；接口05','无已知外敌，不修全国要塞线；不把全部高地认成圣山','GROWTH-03','分散看守/通讯、共同议事，规模随实证需求'),('08','LATER_GROWTH','外部交换与南端大宗运输','远端生产者、少量商人','CONDITIONAL','有盈余与航行条件才成立','09→外部未定方向','外部伙伴/航线/港深未知，不把箭头画成既有全球贸易','GROWTH-04','保留比较选项而非强制港城')]
for no,level,why,users,mag,freq,dep,ext,stage,response in data:demands.append({'id':'DEMAND-'+no,'level':level,'why_driver':why,'users':users,'magnitude':mag,'frequency':freq,'spatial_dependencies':dep,'externalities':ext,'maturity_stage':stage,'possible_spatial_responses':response,'authority':'DESIGN_PROPOSAL'})
save('demand-matrix.json',demands)
flows=[{'id':'FLOW-01','origin':['REGION-01'],'destination':['REGION-02','REGION-03'],'goods':'食物、牲畜、日用品','magnitude':'REGIONAL / seasonal peak','routes':['ROUTE-01','ROUTE-02','ROUTE-09','ROUTE-05'],'reverse':'金属成品/工具，不预设所有原矿送西域','spatial_effect':'转运与储备集中于03/05，居民生产分散于腹地','externality':'牲畜、装卸与公众候渡时间分离；控制损耗'}, {'id':'FLOW-02','origin':['REGION-03'],'destination':['REGION-02','REGION-01'],'goods':'分选后的矿品/石材/成品','magnitude':'REGIONAL_CONDITIONAL','routes':['ROUTE-05','ROUTE-06','ROUTE-07','ROUTE-08'],'reverse':'粮、补给、劳力','spatial_effect':'重货优先就近减重/加工；远端量不足不维持昂贵通道','externality':'烟尘废水与供水/住居不可混为一个下游接收面'}, {'id':'FLOW-03','origin':['REGION-01','REGION-02','REGION-03'],'destination':['CANON-COMMONS'],'goods':'代表、信使、共同誓约与动员','magnitude':'低日常 / 高事件','routes':['ROUTE-03','ROUTE-04'],'spatial_effect':'政治中心保持可达但不夺取所有商业主路','externality':'公地活动峰值与常住人口位阶分开'}, {'id':'FLOW-04','origin':['区域经核实林灌地/水源'],'destination':['各地方生产生活节点'],'goods':'清水、燃料和维护劳动','magnitude':'LOCAL / REGIONAL','routes':[],'spatial_effect':'在下游水源/林料证据前不锁厂址、规模或斜坡开发','externality':'采伐、尾矿、侵蚀与矿水不可由魔法虚化'}]
flows.append({'id':'FLOW-05','origin':['SETTLEMENT-09'],'destination':['SETTLEMENT-05'],'goods':'条件性批量矿品/石材；返程粮食','magnitude':'REGIONAL_CONDITIONAL','routes':['ROUTE-10'],'spatial_effect':'仅在航行和货量成立时，与跨山段比较维护/换载成本；不能用水线长度证明可航','externality':'岸端装卸与水源/居民分离；天气停航需储备'})
save('flows-externalities.json',flows)
anchors=[]
for i,n in enumerate(plan['nodes']):anchors.append({'id':'ANCHOR-'+n['id'][-2:],'scale':'POLITY_TERRITORY','authority':'DESIGN_PROPOSAL','node':n['id'],'role':'STABILIZING_ANCHOR' if n['id'].endswith('04') else 'ORIGIN_ANCHOR' if n['historical_stage']=='GROWTH-01' else 'GROWTH_ANCHOR','why':n['why'],'when':n['historical_stage'],'attracts':n['users'],'repels':n['downstream_implication'],'morphology':n['catchment'],'removal_effect':'04：共同议事流消失，03/05仍可贸易；不得把Canon实际删掉。' if n['id'].endswith('04') else '依赖此节点的流改道、降低专业化或改为季节服务；不保留同等密度与同一条末端路。'})
plan['anchors']=anchors
spaces=[{'id':'SPACE-01','authority':'DESIGN_PROPOSAL','controller':'西域地方共同体/农牧权利者，具体地权待定','users':'农牧户','use':'连续生产与季节放牧','when':'常年/季节交替','why_not_built_over':'生产是聚落存在条件，集市边缘不能自动转成均匀住宅','geometry':'REGION-01内部未定农业地块，不输出精确农田面域'}, {'id':'SPACE-02','authority':'APPROVED_CANON','controller':'三席共同拥有','users':'联盟成员','use':'联盟公地；本轮不重定详细功能容量','when':'制度持续、活动间歇','why_not_built_over':'无单域侵占/再缩小第二行政公地的权利','geometry':'CANON-COMMONS'}, {'id':'SPACE-03','authority':'DESIGN_PROPOSAL','controller':'地方水源/山地公共资源权利者待明确','users':'住民、生产者','use':'清水保护/侵蚀缓冲/燃料更新与通行留地','when':'长期','why_not_built_over':'洁净补给与坡面稳定约束生产扩张','geometry':'具体水源/排水/坡体未验证，禁止以此虚构固定保护半径'}]
plan['commons_negative_spaces']=spaces;save('planning-objects.json',plan)
growth=[{'id':'GROWTH-01','authority':'PLANNING_ASSUMPTION','driver':'地方生计、低地可占地与山地共同体各自组织','response':'低岛分散生活/生产及周期会聚，山地存在低强度混合生计与本地服务；不是成熟矿业人口先行','new_constraint':'已有季节往来与共同体土地关系，使后来集市不随意搬动','next_pressure':'地方剩余与工具需求促成跨水交换','standalone_viability':'若后来没有联盟，仍是地方小规模自给+有限交换；不预留未来议会大道'}, {'id':'GROWTH-02','authority':'PLANNING_ASSUMPTION','driver':'丰余、矿工专业化及转运损耗','response':'03/05成为接口，05→06驮运接续；商业流直接到转换地','new_constraint':'服务投放、到达习惯和权利关系增加迁移成本','next_pressure':'争端、公共工程和交换规则需要共同协商','standalone_viability':'双边季节贸易即能支持共享服务，不需要未来议会或港城'}, {'id':'GROWTH-03','authority':'PLANNING_ASSUMPTION','driver':'三席联盟及已批准共同领土制度','response':'04获得政治位阶；议事流与商业流分叉，维护东connector通达','new_constraint':'共同主权不能被中域通行费或西域飞地吃掉；旧贸易不全搬公地','next_pressure':'远端共同体纳入交换并要求较近日常服务','standalone_viability':'以现有西北核心和有限山地网络运作，不依赖09外贸'}, {'id':'GROWTH-04','authority':'PLANNING_ASSUMPTION','driver':'只有在水粮/资源/通行规模得到支持后，远端交换深化','response':'07/08分段服务，09参与陆海比选；失败则不升级常年中心','new_constraint':'山地地方权利、供水与生态成本限制扩张','next_pressure':'维护成本、资源衰退或航路中断可能导致节点降级','standalone_viability':'南端可保持季节生产与地方互助，不要求永远增长','contraction':'09量不足撤回季节集运；保留地方土地关系和维护通道，不强行维持大港'}]
save('growth-sequence.json',growth)
program=[{'id':'PROGRAM-01','demand_refs':['DEMAND-01','DEMAND-05'],'scope':'REGION-01','required_functions':['生产腹地的生活/维护','周期交易与储备','分散水粮保障'],'dedicated_buildings':'不规定；先验证需求是否可嵌入家庭/共有空间','kit_requirements':['平地生产与居住互接','可增长的混合市场与服务接口','财富/地权/季节强度差异'],'status':'HYPOTHESIS'}, {'id':'PROGRAM-02','demand_refs':['DEMAND-03','DEMAND-04'],'scope':'REGION-02 / CANON-COMMONS','required_functions':['贸易换载与候渡','联盟独立公众到达','货运与议事流可分离'],'dedicated_buildings':'不提供会堂或仓库的精确尺度','kit_requirements':['岸陆/坡麓高差适应','公共入口与货运接口区分','身份连续但不复制同一整栋'],'status':'HYPOTHESIS'}, {'id':'PROGRAM-03','demand_refs':['DEMAND-02','DEMAND-05','DEMAND-06'],'scope':'REGION-03','required_functions':['共同体日常服务','就近减重加工','燃料更新/清水/废物界面'],'dedicated_buildings':'实际矿口/规模未核前不列矿城建筑数','kit_requirements':['断续台地与维护通路适应','污染工序与洁净生活关系','年龄/山坡/权属/工种改变构型'],'status':'HYPOTHESIS'}]
save('building-program.json',program)
packages=[]
for i,reg in enumerate(regions,1):packages.append({'id':f'PACKAGE-0{i}','scale':'REGIONAL_SYSTEM','recipient':'next minecraft-planner','scope_ref':reg['id'],'why':reg['formation'],'planner_fixed':['保留本轮提出的节点角色关系；节点搜索点可由更精细证据修订',reg['expansion'],'遵守已批准三席/公地主权，不得以自然粗分区替代地籍'],'builder_adaptable':['exact footprint','Plan/Section','结构、屋顶、立面、开口','palette / Minecraft translation','局部地形和详细路径实现'],'regional_planner_to_resolve':['实际可用地/供水/地权/既有对象','节点规模与catchment','路线纵断与季节可用性','下钻后的建筑/组团包和边界'],'dependencies':['EVIDENCE-REFRESH',f'PROGRAM-0{i}'],'historical_growth_stage':['GROWTH-01','GROWTH-02','GROWTH-03','GROWTH-04'],'world_write_authorization':False,'direct_builder_ready':False,'reason_not_direct_build':'L0交接到L1；尚无parcel/envelope，不向Builder伪造可直接施工包','conflict_protocol':'UPSTREAM_PLANNING_ISSUE：附证据、冲突关系与最小修订对象，回退受影响Morphology/Handoff Gate'})
save('implementation-packages.json',{'state':'HANDOFF_READY','scope_of_ready':'国家尺度到区域Planner的约束交接；非建筑施工就绪','packages':packages,'implementation_sequence':[{'step':1,'action':'GPT+Owner审核本提案；不修改Canon','world_writes':0},{'step':2,'action':'更新关键水源/岸端/坡地证据，比较A/B运输分支','world_writes':0},{'step':3,'action':'先完成共享跨域接口关系，再分别下钻三域；不按历史阶段机械复制施工批次','world_writes':0},{'step':4,'action':'L1→L2→必要L3/L4后产出具体Builder packages；另取得world-write授权','world_writes':0}]})
sources=[]
whitelist=[('E-CANON','minecraft/建筑师/world/civilizations/CIV-001/README.md','APPROVED_CANON'),('E-ATLAS','minecraft/建筑师/research/natural-geography/NG-3/manifest/atlas.json','DERIVED'),('E-R1','minecraft/建筑师/research/human-geography/southern-island/WB-002R-R1/manifest/profile.json','DERIVED'),('E-SCOPE','minecraft/建筑师/research/human-geography/southern-island/WB-002R-R1/profile/scope-completion.json','DERIVED'),('E-STORE','minecraft/建筑师/research/human-geography/southern-island/WB-002R-R1/manifest/store.json','DERIVED')]
commit=subprocess.check_output(['git','rev-parse','origin/main'],cwd=repo,text=True).strip()
for ident,p,authority in whitelist:
 data=subprocess.check_output(['git','show',commit+':'+p],cwd=repo);dest=R/'sources'/f'{ident}{Path(p).suffix}';dest.write_bytes(data);sources.append({'id':ident,'path':p,'git_commit':commit,'sha256':sha(dest),'authority':authority,'freshness':'已接受调查/Canon的仓库版本；非当日世界重扫','used_for':'身份/尺度/阻力/边界约束'})
for p in (R/'sources/skill').rglob('*.md'):sources.append({'id':'SKILL-'+p.stem,'url':'https://github.com/zhangchenjia21-dot/Vibe-Coding/blob/main/skill/codex/minecraft-planner/'+p.relative_to(R/'sources/skill').as_posix(),'sha256':sha(p),'authority':'OWNER_CONSTRAINT','version':'v0.1','retrieved':'2026-09-13','immutable_evidence':p.relative_to(R).as_posix()})
for p,kind in [(SRC/'raw-or-queryable/observed.sqlite.gz','OBSERVED'),(SRC/'raw-or-queryable/derived.npz','DERIVED'),(G/'natural-geography/NG-3/atlas/objects.jsonl','DERIVED')]:sources.append({'id':'DATA-'+p.stem,'path':p.relative_to(repo).as_posix(),'sha256':sha(p),'authority':kind,'selected_fields':'samples x,z,exposed_y only; derived land_component,slope8 only; atlas NGEO/NHYD within study only','not_used':'targets,assessments,zones,k2/k3/k4/k5及任何人文方案'})
save('source-register.json',{'sources':sources,'world_reads':0,'world_writes':0,'sampling_note':'snapshot样本107712列；不是新世界调查','isolation':'不读取后续人文规划、G1/N1/Middle、Architecture Design或其评审；WB-003R也未读取，避免混入既有经济规划。Canon入口的自含文字保留。','prior_context_caveat':'同一会话早前出现过项目状态摘要；本轮不调用其方案内容作为依据，无法声称新会话级盲测。'})
# 交互只提供图层/阶段切换和节点资料，数据不发生远程调用。
buttons=''.join(f'<button onclick="show(\'{v}\')">{t}</button>' for v,t in [('territory','整体结构'),('flows','交通与流'),('growth-1','生长1'),('growth-2','生长2'),('growth-3','生长3'),('growth-4','生长4')])
rows=''.join('<tr><td>'+n['id']+'</td><td>'+html.escape(n['name'])+'</td><td>'+str(n['geometry']['coordinates'])+'</td><td>'+html.escape(n['why'])+'</td></tr>' for n in plan['nodes'])
(R/'index.html').write_text('<!doctype html><meta charset="utf-8"><title>MP-P01 三域联盟规划</title><style>body{font:17px system-ui;background:#f0efe5;color:#223333;margin:28px}button{padding:10px;margin:4px;cursor:pointer}img{width:100%;max-width:1780px}td{padding:12px;border-bottom:1px solid #aaa}table{border-collapse:collapse}a{color:#235c81}</style><h1>三域联盟：生产腹地、转换接口与多点山地网络</h1><p>MP-P01 / r1 / HANDOFF_READY（到区域 Planner） · DESIGN_PROPOSAL · world writes=0</p><p>坐标点为搜索代表，路线为抽样候选；不是已建城镇或道路。资料与提案分开，完整因果和分支见 <a href="settlement-plan.md">规划方案</a>。</p>'+buttons+'<div><img id="map" src="maps/territory.png"></div><h2>节点及形成理由</h2><table>'+rows+'</table><script>function show(n){document.getElementById("map").src="maps/"+n+".png"}</script>',encoding='utf8')
print('planning packet and provenance written')
