const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/MRVHREVO/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const root=path.resolve(__dirname,'..'),browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'}),page=await browser.newPage({viewport:{width:1600,height:1000},acceptDownloads:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(pathToFileURL(path.join(root,'index.html')).href);await page.waitForFunction(()=>document.querySelector('#message').textContent.includes('QA 已更新'));assert.match(await page.locator('#stats').innerText(),/2,150,896/);
await page.locator('#confirm').click();assert.match(await page.locator('#message').innerText(),/Owner/);
const target=await page.evaluate(()=>{const b=TERRITORY_BASE;for(let z=b.bounds[1]+600;z<b.bounds[3];z++)for(let x=b.bounds[0]+500;x<b.bounds[2]-500;x++)if([-8,0,8].every(dx=>[-8,0,8].every(dz=>editor.at(x+dx,z+dz)===4)))return {x,z};});
// 使用真实指针在全图定位，再放大到逐格；坐标换算由显示范围独立计算。
const box=await page.locator('#map').boundingBox(),base=await page.evaluate(()=>({w:TERRITORY_BASE.width,h:TERRITORY_BASE.height,b:TERRITORY_BASE.bounds}));const sc=Math.min(box.width/base.w,box.height/base.h),px=box.x+(box.width-base.w*sc)/2+(target.x-base.b[0]+.5)*sc,py=box.y+(box.height-base.h*sc)/2+(target.z-base.b[1]+.5)*sc;await page.mouse.move(px,py);await page.mouse.wheel(0,-4000);await page.waitForTimeout(100);const before=await page.evaluate(()=>editor.qa().areas[1]);await page.mouse.click(px,py);const after=await page.evaluate(()=>editor.qa().areas[1]);assert.equal(after-before,1);await page.locator('#undo').click();assert.equal(await page.evaluate(()=>editor.qa().areas[1]),before);await page.locator('#redo').click();assert.equal(await page.evaluate(()=>editor.qa().areas[1]),after);
await page.locator('#mode').selectOption('rect');await page.mouse.move(px,py);await page.mouse.down();await page.mouse.move(px+30,py+30);await page.mouse.up();assert.ok(await page.evaluate(()=>editor.qa().areas[1])>after);await page.locator('#undo').click();await page.locator('#undo').click();assert.equal(await page.evaluate(()=>editor.qa().areas[1]),0);
const saved=page.waitForEvent('download');await page.locator('#save').click();const save=await saved;await save.saveAs(path.join(root,'测试/临时/restore.json'));await page.locator('#load').setInputFiles(path.join(root,'测试/临时/restore.json'));assert.match(await page.locator('#message').innerText(),/草稿已修改/);await page.locator('#base').selectOption('biome');await page.locator('#territory').uncheck();await page.locator('#base').selectOption('terrain');await page.locator('#territory').check();await page.locator('#fit').click();await page.locator('#qa').click();await page.waitForFunction(()=>document.querySelector('#message').textContent.includes('QA 已更新'));await page.screenshot({path:path.join(root,'validation/工作台预览.png')});
const download=page.waitForEvent('download');await page.locator('#export').click();const d=await download;await d.saveAs(path.join(root,'测试/临时/example.zip'));await page.locator('#owner').fill('TEST OWNER');await page.locator('#ack').check();const confirmed=page.waitForEvent('download');await page.locator('#confirm').click();await(await confirmed).saveAs(path.join(root,'测试/临时/confirmed.zip'));
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(root,'validation/浏览器结果.json'),JSON.stringify({status:'PASS',browser:await browser.version(),protocol:'file://',checks:['offline load','initial QA counts','formal confirmation guard','real pointer one-column edit','undo redo','rectangle','layer toggles','save and file-input import','draft ZIP','Owner confirmed ZIP'],pageErrors:errors},null,2));await browser.close();console.log('browser PASS');})().catch(e=>{console.error(e);process.exit(1);});
