(function(g){'use strict';const C=g.TerritoryContract;
function encode(m,status,owner){const runs=[];for(let z=0;z<m.h;z++)for(let x=0;x<m.w;){const c=m.values[z*m.w+x],start=x++;while(x<m.w&&m.values[z*m.w+x]===c)x++;if(c!==255)runs.push([z+m.base.bounds[1],start+m.base.bounds[0],x-1+m.base.bounds[0],c]);}return {schema:C.SCHEMA,status,owner:owner||null,exportedAt:new Date().toISOString(),revision:m.revision,source:{id:m.base.id,bounds:m.base.bounds,freshness:m.base.freshness,references:m.base.references},categories:C.categories.map(c=>c.id),coordinateConvention:'inclusive [z,x0,x1,categoryIndex]; block-column area = 1',runs};}
// 完整覆盖、来源绑定和无重叠校验全部成功后才允许替换内存状态。
function decode(doc,m){if(doc.schema!==C.SCHEMA||doc.source?.id!==m.base.id||JSON.stringify(doc.source.bounds)!==JSON.stringify(m.base.bounds)||JSON.stringify(doc.categories)!==JSON.stringify(C.categories.map(c=>c.id))||!Array.isArray(doc.runs))throw Error('格式、底图来源或类别不匹配');const v=new Uint8Array(m.n);v.fill(255);let count=0;for(const row of doc.runs){if(!Array.isArray(row)||row.length!==4||!row.every(Number.isInteger))throw Error('无效 RLE');const [z,a,b,c]=row;if(a>b||!C.validCode(c)||m.index(a,z)<0||m.index(b,z)<0)throw Error('RLE 越界');for(let x=a;x<=b;x++){const i=m.index(x,z);if(m.values[i]===255||v[i]!==255)throw Error('RLE 水域或重叠');v[i]=c;count++;}}if(count!==m.landCount)throw Error('RLE 未完整覆盖陆地');return v;}
const table=Uint32Array.from({length:256},(_,n)=>{for(let k=0;k<8;k++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0;});
function crc(b){let c=0xffffffff;for(const v of b)c=table[(c^v)&255]^(c>>>8);return (c^0xffffffff)>>>0;}
// 无压缩 ZIP 保持纯浏览器、file:// 离线运行；每个文件使用标准 CRC32。
function zip(files){const chunks=[],central=[];let offset=0;const enc=new TextEncoder();for(const [path,raw] of Object.entries(files)){const name=enc.encode(path),b=typeof raw==='string'?enc.encode(raw):raw,checksum=crc(b),h=new Uint8Array(30+name.length),d=new DataView(h.buffer);d.setUint32(0,0x04034b50,true);d.setUint16(4,20,true);d.setUint32(14,checksum,true);d.setUint32(18,b.length,true);d.setUint32(22,b.length,true);d.setUint16(26,name.length,true);h.set(name,30);chunks.push(h,b);const q=new Uint8Array(46+name.length),v=new DataView(q.buffer);v.setUint32(0,0x02014b50,true);v.setUint16(4,20,true);v.setUint16(6,20,true);v.setUint32(16,checksum,true);v.setUint32(20,b.length,true);v.setUint32(24,b.length,true);v.setUint16(28,name.length,true);v.setUint32(42,offset,true);q.set(name,46);central.push(q);offset+=h.length+b.length;}const end=new Uint8Array(22),e=new DataView(end.buffer),size=central.reduce((n,b)=>n+b.length,0);e.setUint32(0,0x06054b50,true);e.setUint16(8,central.length,true);e.setUint16(10,central.length,true);e.setUint32(12,size,true);e.setUint32(16,offset,true);return new Blob([...chunks,...central,end],{type:'application/zip'});}
g.TerritoryCodec={encode,decode,zip};if(typeof module!=='undefined')module.exports=g.TerritoryCodec;
})(globalThis);
